# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-19 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', models.TextField(verbose_name=' 正文')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='文章状态')),
                ('abstract', models.CharField(blank=True, help_text='可选，如若为空将摘取正文的前54个字符', max_length=54, null=True, verbose_name='摘要')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='评论者名字')),
                ('user_email', models.EmailField(max_length=255, verbose_name='评论者邮箱')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论发表时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipmanager.Article', verbose_name='评论所属文章')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='姓名')),
                ('QQ', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('duty', models.CharField(max_length=200, null=True, verbose_name='职务')),
                ('company_name', models.CharField(max_length=300, null=True, verbose_name='公司名称')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=200, null=True, verbose_name='职务')),
                ('duty_id', models.CharField(max_length=300, null=True, verbose_name='职位编号')),
                ('ship_age', models.CharField(max_length=100, null=True, verbose_name='船龄')),
                ('company_name', models.CharField(max_length=300, null=True, verbose_name='公司名称')),
                ('certificate_level', models.CharField(max_length=200, null=True, verbose_name='职务')),
                ('special_certificate', models.CharField(max_length=300, null=True, verbose_name='特殊证书')),
                ('route_area', models.CharField(max_length=300, null=True, verbose_name='路线区域')),
                ('recruitment_ship', models.CharField(max_length=300, null=True, verbose_name='招聘船型')),
                ('tonnage', models.CharField(max_length=200, null=True, verbose_name='吨位')),
                ('time', models.CharField(max_length=30, null=True, verbose_name='搜索时间')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(choices=[('', '---其他---'), ('整套班子', '整套班子'), ('船长', '船长'), ('大副', '大副'), ('二副', '二副'), ('三副', '三副'), ('白皮三副', '白皮三副'), ('驾助', '驾助'), ('实习三副', '实习三副'), ('GMDSS普通操作员', 'GMDSS普通操作员'), ('水手长', '水手长'), ('木匠', '木匠'), ('水手', '水手'), ('高级水手', '高级水手'), ('二水', '二水'), ('新证水手', '新证水手'), ('实习水手', '实习水手'), ('轮机长', '轮机长'), ('大管轮', '大管轮'), ('二管轮', '二管轮'), ('三管轮', '三管轮'), ('白皮三管', '白皮三管'), ('电机员', '电机员'), ('电工', '电工'), ('轮助', '轮助'), ('实习三管', '实习三管'), ('机工长', '机工长'), ('铜匠', '铜匠'), ('泵匠', '泵匠'), ('机工', '机工'), ('高级机工', '高级机工'), ('新证机工', '新证机工'), ('实习机工', '实习机工'), ('高级水手', '高级水手'), ('大厨', '大厨'), ('服务员', '服务员'), ('船医', '船医')], max_length=70, null=True)),
                ('duty_id', models.CharField(max_length=20, null=True, verbose_name='职务编号')),
                ('ship_age', models.CharField(max_length=10, null=True, verbose_name='船龄')),
                ('company_name', models.CharField(max_length=300, null=True, verbose_name='公司名称')),
                ('certificate_level', models.CharField(choices=[('', '---其他---'), ('甲类', '甲类'), ('乙一', '乙一'), ('乙二', '乙二'), ('丙一', '丙一'), ('丙二', '丙二'), ('丁类', '丁类'), ('长一', '长一'), ('长二', '长二'), ('内河', '内河')], max_length=200, null=True, verbose_name='证书等级')),
                ('special_certificate', models.CharField(choices=[('', '---其他---'), ('化高证书', '化高证书'), ('油高证书', '油高证书'), ('液高证书', '液高证书'), ('油化双证', '油化双证'), ('客滚船证书', '客滚船证书'), ('海进江证书', '海进江证书'), ('外籍签注适任证书', '外籍签注适任证书'), ('高速船证书', '高速船证书')], max_length=300, null=True, verbose_name='特殊证书')),
                ('route_area', models.CharField(choices=[('', '---其他---'), ('中日韩', '中日韩'), ('东南亚', '东南亚'), ('中东波斯湾', '中东波斯湾'), ('地中海', '地中海'), ('南北美', '南北美'), ('环球航线', '环球航线'), ('内河航线', '内河航线'), ('江海航线', '江海航线'), ('长江航线', '长江航线')], max_length=300, null=True, verbose_name='路线区域')),
                ('recruitment_ship', models.CharField(choices=[('', '---其他---'), ('散杂货船', '散杂货船'), ('集装箱船', '集装箱船'), ('多用途船', '多用途船'), ('油轮', '油轮'), ('化学品船', '化学品船'), ('油化船', '油化船'), ('液化气船', '液化气船'), ('工程船', '工程船'), ('冷藏船', '冷藏船'), ('港作船', '港作船'), ('LNG动力船', 'LNG动力船'), ('客船', '客船'), ('客滚船', '客滚船'), ('滚装汽车船', '滚装汽车船'), ('拖轮', '拖轮'), ('作业渔船', '作业渔船'), ('打桩船', '打桩船'), ('邮船', '邮船'), ('沥青船', '沥青船'), ('木材船', '木材船'), ('泵船', '泵船'), ('工作船', '工作船'), ('邮政船', '邮政船'), ('海监船', '海监船'), ('救援船', '救援船'), ('不上船', '不上船')], max_length=300, null=True, verbose_name='招聘船型')),
                ('tonnage', models.CharField(choices=[('', '---其他---'), ('5千吨以下', '5千吨以下'), ('5千吨-1万吨', '5千吨-1万吨'), ('1万吨-2万吨', '1万吨-2万吨'), ('2万吨-3万吨', '2万吨-3万吨'), ('3万吨-6万吨', '3万吨-6万吨'), ('6万吨-10万吨', '6万吨-10万吨'), ('10万吨-15万吨', '10万吨-15万吨'), ('15万吨-30万吨', '15万吨-30万吨'), ('30万吨以上', '30万吨以上')], max_length=200, null=True, verbose_name='吨位')),
                ('time', models.CharField(choices=[('', '---其他---'), ('一星期内', '一星期内'), ('一个月内', '一个月内'), ('三个月内', '三个月内'), ('一年以内', '一年以内')], max_length=300, null=True, verbose_name='搜索时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('duty', models.CharField(default=False, max_length=200, verbose_name='职务')),
                ('duty_id', models.CharField(max_length=300, null=True, verbose_name='职位编号')),
                ('ship_age', models.CharField(max_length=100, null=True, verbose_name='船龄')),
                ('company_name', models.CharField(max_length=300, null=True, verbose_name='公司名称')),
                ('certificate_level', models.CharField(max_length=200, null=True, verbose_name='职务')),
                ('special_certificate', models.CharField(max_length=300, null=True, verbose_name='特殊证书')),
                ('route_area', models.CharField(max_length=300, null=True, verbose_name='路线区域')),
                ('recruitment_ship', models.CharField(max_length=300, null=True, verbose_name='招聘船型')),
                ('tonnage', models.CharField(max_length=200, null=True, verbose_name='吨位')),
                ('time', models.CharField(max_length=300, null=True, verbose_name='搜索时间')),
            ],
        ),
    ]
